# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 22:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime201',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=21)),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('wkt', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2010',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=21)),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('wkt', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=21)),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('wkt', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2012',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=21)),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('wkt', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2013',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=21)),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('wkt', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=21)),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('wkt', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=21)),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('location', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('wkt', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
