# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 20:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_crime_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadcdwid', models.CharField(max_length=254)),
                ('eventnum', models.CharField(max_length=21)),
                ('offensenum', models.IntegerField()),
                ('eventcode', models.IntegerField()),
                ('descriptio', models.CharField(max_length=254)),
                ('subgroup', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('block', models.CharField(max_length=254)),
                ('district', models.CharField(max_length=254)),
                ('zonebeat', models.CharField(max_length=254)),
                ('census', models.CharField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=-1)),
            ],
        ),
        migrations.DeleteModel(
            name='Crime201',
        ),
        migrations.DeleteModel(
            name='Crime2010',
        ),
        migrations.DeleteModel(
            name='Crime2011',
        ),
        migrations.DeleteModel(
            name='Crime2012',
        ),
        migrations.DeleteModel(
            name='Crime2013',
        ),
        migrations.DeleteModel(
            name='Crime2015',
        ),
        migrations.DeleteModel(
            name='Crime2016',
        ),
    ]
