# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_crime_app', '0003_auto_20160525_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimemodel',
            name='offensenum',
            field=models.IntegerField(default=0),
        ),
    ]
