# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_crime_app', '0007_auto_20160525_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimemodel',
            name='eventnum',
            field=models.FloatField(),
        ),
    ]
